# Generated by Django 5.2.5 on 2025-08-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="registration_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
